services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: cmcp-test
    volumes:
      # Mount source code for live changes during development
      - ./:/app:ro
    command: ["/bin/bash", "-c", "cd /app && go build -o cmcp && ./tests/test-comprehensive.sh"]
    environment:
      - HOME=/root
    # Ensure clean environment
    tmpfs:
      - /tmp
      - /root